### ISSUE TITLE
No pictures at rubydoc.info for glimmer-dsl-libui (URL example: https://www.rubydoc.info/gems/glimmer-dsl-libui/0.5.1 )

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-libui#19]
Hey there Andy,

Not sure if this is worth reporting, since github is the primary area-of-interest for
glimmer-dsl-libui, but just in case you are not aware of it I'll report this here as
well.

If you go to:

https://www.rubydoc.info/gems/glimmer-dsl-libui/0.5.1

aka the rubydoc site for glimmer, then it displays the documentation, but not
the images.

For instance, at the Linux entry I see:

glimmer-dsl-libui-linux-basic-window.png

but not the image. I assume for github this is easier because you can refer
to the path where the images are situated. Not sure if there is an easy way
to make them fix on rubydoc as-is; I "work around" by just uploading images
to imgur and then linking to them, but this is more of a hackish approach
than an elegant one. :P

(But perhaps there is some way to refer to the image on rubydoc too, I
really have not researched that. Perhaps one can just link to it too.)

Anyway, this here is just meant as a short report - perhaps it may not even
be worth to fix it as most users just use github anyway, so again, that's just
a short report. Glimmer on! \o/

**Comment by AndyObtiva** [comment]
To fix the images for rubydoc, I'd have to either include the images in the Ruby gem (bad, since it bloats the gem size by a lot for no good reason) or hardcode absolute image paths for the GitHub hosted images (inconvenient and a little bad since it would prevent the right images from showing up when browsing GitHub branches other than master).

To be honest, I think people rarely use the rubydoc for the README (they just use it to browse standard Ruby APIs) and can always click on the GitHub repository to see the images, so I don't think this is an issue worth fixing.
