### ISSUE TITLE
on_key_event? Formfield-  Submit Form with Enter?

### ISSUE THREAD

**Issue by Delikt** [AndyObtiva/glimmer-dsl-libui#26]
Is it possible to input Userdata in a Textfield (Login Form) and submit it with pressing Enter instead of building a "Login" Button to submit Login?

a Example snippet will be welcome.

Thanks!

**Comment by Delikt** [comment]
Thank you for your fast response, i will try around with that but i'm pretty sure this will not work cause i have a password_entry Field from where i want to submit.. i will reply here if the workaround worked for me

**Comment by AndyObtiva** [comment]
Yeah, no... that only works for standard text `entry` because `non_wrapping_multiline_entry` does not support a password mask like `password_entry`.

However, a workaround is to add a submit button below the `password_entry`, which the user can invoke using the keyboard alone with the following keys:
1. TAB
2. SPACE

```ruby
require 'glimmer-dsl-libui'

include Glimmer

window('Submit with Keyboard', 250, 40) {
  vertical_box {
    password_entry { |nwme|
      on_changed do
        if nwme.text.include?("\n")
          nwme.text = nwme.text.gsub("\n", '')
          msg_box('Submission', "You entered:\n #{nwme.text}")
        end
      end
    }
    button {
      text 'Submit'
      
      on_clicked do
        msg_box 'Submitted', 'Hitting tab and space triggers the submit button'
      end
    }
  }
}.show
```

![Screen Shot 2022-05-16 at 10 46 15 AM](https://user-images.githubusercontent.com/23052/168620175-6961397c-cffc-49ee-9fba-8a1ed6af7a4c.png)

![Screen Shot 2022-05-16 at 10 46 19 AM](https://user-images.githubusercontent.com/23052/168620189-d434158a-1c93-4431-8873-f7d482fbad8c.png)

Otherwise, there is one more workaround.

You can build your own ENTER-supporting custom password control using the `area` control (which supports arbitrary keyboard and mouse event listeners). If you really need it and need help building it, let me know, and I'd be happy to provide some code.

**Comment by AndyObtiva** [comment]
Hahaha, I just discovered one more workaround. You can attempt to mask the `non_wrapping_multiline_entry` yourself. I am including an example below, but it is not complete as it does not handle backspacing, deleting, moving the keyboard caret, and other edge cases, but it's just a proof of concept.

```ruby
require 'glimmer-dsl-libui'

include Glimmer

window('Entry Submission with Enter', 300, 50) {
  vertical_box {
    non_wrapping_multiline_entry { |nwme|
      on_changed do
        if nwme.text.include?("\n")
          nwme.text = nwme.text.gsub("\n", '')
          msg_box('Submission', "You entered:\n #{@saved}")
        end
        if nwme.text.match(/[^*]/)
          @saved ||= ''
          @saved += nwme.text.match(/([^*])/)[1]
          nwme.text = nwme.text.gsub(/[^*]/, '*')
        end
      end
    }
  }
}.show
```

![Screen Shot 2022-05-16 at 10 53 14 AM](https://user-images.githubusercontent.com/23052/168621881-6093a58c-3fe6-4a91-8ab4-d8f25facb634.png)

![Screen Shot 2022-05-16 at 10 53 17 AM](https://user-images.githubusercontent.com/23052/168621890-567a3104-efa3-4168-8f26-48ec729df033.png)

**Comment by Delikt** [comment]
Thank you very much for your Time and this workarounds, in my pov it make more sense to press TAB and SPAVE instead of TAB and Enter and the behavor not to handle backspacing, deleting, moving isn't that pretty... so i will let it is like it is for now... 

Here a preview of my first Programm ever, what i builded with Ruby, LibUI, glimmer-dsl-libui and ocra to compile a self executable Windows exe:

![Peek 2022-05-18 10-34](https://user-images.githubusercontent.com/22080674/168995877-b4e4494b-f8a2-4110-90e6-9fcade0d9ed3.gif)

Thanks to all the Programers from the above mentationed Repos, who makes this happen! 

This Program is a configurable Setup what i coded for my Work in my spare Time - it save me as IT Support a lot of Time.

Sadly, i can't puplish the Source, cause there are some stuff in the Code from my Company.
