### ISSUE TITLE
Are there file and folder pickers?

### ISSUE THREAD

**Issue by MtnBiker** [AndyObtiva/glimmer-dsl-libui#34]
I'm looking a simple macOS app in Ruby, but need to pick files and folders. I can do this with Pashua, but it's not being actively supported. 

If not what should I consider?

Thank you

**Comment by kojix2** [comment]
Hi @MtnBiker

You can use `open_file` and `save_file` in Glimmer DSL LibUI.
https://github.com/AndyObtiva/glimmer-dsl-libui#extra-dialogs

Or is it something more different that you are looking for?

**Comment by MtnBiker** [comment]
@kojix2 Looks like it. Now I'll try to look at glimmer-dsl-libui to sort out the syntax.

Thank you

**Comment by AndyObtiva** [comment]
@MtnBiker For selecting files, whatever @kojix2 mentioned is correct. 

For selecting directories, that would be open_folder, but it won't be available until the next [libui-ng](https://github.com/libui-ng/libui-ng/blob/master/CHANGELOG.md) C library release (a glimmer-dsl-libui included dependency), which should happen hopefully in the near future. 

Otherwise, today, you could use [Glimmer DSL for Tk](https://github.com/AndyObtiva/glimmer-dsl-tk) with the Tk.chooseDirectory call to open a directory. 

Alternatively, you could use [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) in JRuby, which supports directory_dialog.open (as demonstrated in [Hello, Directory Dialog!](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_SAMPLES.md#hello-directory-dialog))

**Comment by AndyObtiva** [comment]
Hi, I just wanted to note that I just released [`glimmer-dsl-libui` version 0.6.0.pre.0](https://rubygems.org/gems/glimmer-dsl-libui/versions/0.6.0.pre.0), which finally supports a newer version of the C libui library (the newer libui-ng), including support for `open_folder` (a variation on `open_file` that can open a directory).
