### ISSUE TITLE
Using a single local image, such as foobar.png ?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-libui#4]
Hey there Andy,

I want to test glimmer-dsl-libui finally more seriously; the first project
will be backup_paradise. One part of it is used by another elderly
person on windows (to back up things; I tested this via the 
commandline already on windows, and ruby.exe works fine
with it), so I want to make this part as convenient as
possible in a GUI manner, so that just a single button has to
be clicked. This also works as-is but it is not pretty and I 
lack the knowledge to improve libui_paradise. (I won't
abandon libui_paradise but I treat it more as a research project
at this time; the whole glimmer suite is LIGHTYEARS ahead of
it, which is good, so a minor reason for me adding glimmer
code to backup_paradise will be to simply extend all 
possible options in this regard.)

Currently glimmer-dsl-libui has a few examples where an image
is used.

For example in the documentation you show a screenshot of:

Basic Table Image

So we know that images work.

Could you also perhaps add a simple example that shows just
how ONE image can be used? Something like:

- a libui label ('Hello world')
- a field for the image at hand
- last but not least the actionable button e. g. "submit" (or back up, but submit
 is probably more generic and better for an example)

I would like to add a few simple icons to the GUI that I plan to use,
but right now I am not entirely sure how to do so. The Basic Table
Image example does not seem to be 1:1 what I may want to do;
e. g. I have images for a harddrive and I just want to add it to
provide simple cues where to click. I could probably already 
re-purpose Basic Table, but the whole project that I will try will
also be me using glimmer-dsl-libui and glimmer, and that takes
a little learning, so this is a very noobish question indeed.

Hopefully I could explain the use case, so to TL;DR it:

- **Would it be possible to add a simple example to glimmer-dsl-libui
for a local image being displayed?** (I guess it is fine to use
system('wget '+url_to_a_remote_image) and then use it,
so the image does not even have to be distributed as-is. But
either way, I am sure if you consider the described use case
useful then you'll solve it either way. On a side note I saw
the tetris example - I think you have some generic tetris
entry point at glimmer too. May be useful to perhaps add an
entry to glimmer directly and mention which GUI variants
have support for tetris. Sorry to distract with this, I just wanted
to mention it briefly, without creating too many separate issues.)

**Comment by AndyObtiva** [comment]
What you ask for is not supported in C [libui](https://github.com/andlabs/libui) yet (for example, the [golang LibUI docs](https://pkg.go.dev/github.com/andlabs/ui) do not provide any way of rendering images outside of table)

However, I just succeeded in the impossible task of supporting image rendering without C [libui](https://github.com/andlabs/libui) officially supporting it (with several documented caveats to keep in mind):

![image](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-libui/master/images/glimmer-dsl-libui-mac-basic-image.png)

I added an `image(file, width, height)` Glimmer custom widget that can be nested under `area`, fully documented over here:
https://github.com/AndyObtiva/glimmer-dsl-libui#image-glimmer-custom-control

I also added an example of using it with many variations and subtle differences:
https://github.com/AndyObtiva/glimmer-dsl-libui#basic-image

Of course, to address your inquiry about examples of `label`s and `button`s, please keep in mind that `area` is very versatile since it can draw text just like label and can accept keyboard and mouse events just like button as demonstrated in the Area Gallery example:
https://github.com/AndyObtiva/glimmer-dsl-libui#area-gallery

One final note is that in Linux, table images grow and shrink with the image size unlike on the Mac where table row heights are constant regardless of image sizes. As such, you may be able to repurpose a table with a single image column and a single row as an image control with more native libui rendering if you are only targeting Linux with your app.

That should address your needs for the time being.

Happy Glimmering!

p.s. About Tetris, you can already run it indirectly via the [Meta-Example](https://github.com/AndyObtiva/glimmer-dsl-libui#examples) or directly via one of these commands:

Run with this command from the root of the project if you cloned the project:

```
ruby -r './lib/glimmer-dsl-libui' examples/tetris.rb
```

Run with this command if you installed the [Ruby gem](https://rubygems.org/gems/glimmer-dsl-libui):

```
ruby -r glimmer-dsl-libui -e "require 'examples/tetris'"
```

**Comment by AndyObtiva** [comment]
I just added web URL file support for `image` in addition to local file path support.

Example:

```ruby
# frozen_string_literal: true

require 'glimmer-dsl-libui'

include Glimmer

window('Basic Image', 96, 96) {
  area {
    on_draw do |area_draw_params|
      image('https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-libui/master/icons/glimmer.png', 96, 96)
    end
  }
}.show
```

![screenshot](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-libui/master/images/glimmer-dsl-libui-windows-basic-image.png)
