### ISSUE TITLE
a 'table' should have a 'on_selected' listener

### ISSUE THREAD

**Issue by rempargo** [AndyObtiva/glimmer-dsl-libui#41]
It seems that the 'table' keyword only has two listeners, 'on_changed' and 'on_edited', but it would be nice to also have a listener 'on_selected' (like a combobox) which returns either the row (if one row is selected) or an array of rows (if multiple rows are selected.)

**Comment by AndyObtiva** [comment]
Yes, this is coming up in a future version of the underlying C libui-ng library:
https://github.com/libui-ng/libui-ng/pull/73

In order to expose the new Table Selection API in Glimmer DSL for LibUI, I would need the Ruby LibUI FFI binding author to expose it, so I created an issue request to its author to get that done:
https://github.com/kojix2/LibUI/issues/69

As soon as that is done and there is a new release, I will make a release in Glimmer DSL for LibUI that provides access to Table Selection via a friendly API listener, like `on_selection_changed`, matching the underlying C API.

**Comment by rubyFeedback** [comment]
(This is mostly for Andy) If that may be possible at a later time, perhaps you could mention it. I would like to have a look at how this works. Being able to respond to on-selection events would appear rather useful indeed.

**Comment by AndyObtiva** [comment]
@rubyFeedback I received help from the LibUI binding author regarding how to expose that newly implemented functionality of LibUI and I am actually in progress on adding it to Glimmer DSL for LibUI. I’ll post back here when I’m done.

**Comment by AndyObtiva** [comment]
OK, I just [released version 0.0.7](https://rubygems.org/gems/glimmer-dsl-libui/versions/0.7.0) with the following changes:
- Upgrade to libui v0.1.2.pre (including newer libui-ng with table selection API)
- `table` `on_row_clicked`, `on_row_double_clicked`, and `on_selection_changed` listeners
- `table` `selection` property (including `selection=` attribute writer)
- `table` `selection_mode` property supporting values: `:zero_or_many` , `:none` , `:zero_or_one` , and `:one`
- Support `radio_buttons` `selected` value of `nil`, treating as `-1` to clear selected radio button.
- `examples/basic_table_selection.rb`

So, now you can use `on_selection_changed` for selection changes, or one of the other listeners, `on_row_clicked` & `on_row_double_clicked`, if you need to capture a click or double click on a table row.

There is a new example that demonstrates the new table selection API completely:
https://github.com/AndyObtiva/glimmer-dsl-libui/blob/master/examples/basic_table_selection.rb

This addresses the issue completely, so I am going to close it.

If you have any further questions, feel free to post back here, in the [Glimmer Gitter chat](https://app.gitter.im/#/room/#AndyObtiva_glimmer:gitter.im), or even reopen the issue if you encounter a problem.

Cheers.

**Comment by AndyObtiva** [comment]
[Version 0.7.1 has been released](https://rubygems.org/gems/glimmer-dsl-libui/versions/0.7.1) with more Table Selection API features:
- `table` column `on_clicked` listener (can be nested under `text_column`, `text_color_column`, `button_column`, `checkbox_column`, `checkbox_text_color_column`, `image_column`, `image_text_color_column`, `image_text_column`, and `progress_bar_column`)
- `table` column `sort_indicator` property (can be `nil`, `:ascending` [aliases: `:asc`, `:a`], `:descending` [aliases: `:desc`, `:d`])
- `table` column `set_sort_indicator` alias for `sort_indicator=` can accept an option of `reset_columns: false` to avoid resetting sort indicator of other columns when setting sort indicator on a specific column
- `table` `header_visible` property (Boolean)
- Fix issue with `table` `selection_mode` getting set to `nil` if not specified

The table selection example has been updated to demonstrate the new features:
https://github.com/AndyObtiva/glimmer-dsl-libui/blob/master/examples/basic_table_selection.rb

![Screen Shot 2023-03-12 at 1 03 42 AM](https://user-images.githubusercontent.com/23052/224527349-8e07843c-7bb1-4cc7-8484-a55712e56112.png)

I recommend using version 0.7.1 going forward because it fixes a discovered issue in 0.7.0.

**Comment by AndyObtiva** [comment]
[Version 0.7.2 & 0.7.3 have been released](https://rubygems.org/gems/glimmer-dsl-libui/versions/0.7.3) with more Table Selection API features, mostly enabling data-binding with the new table selection attributes:

## 0.7.3

- `table` `selection` data-binding support
- `table` column `sort_indicator` data-binding support
- New `examples/basic_table_selection2.rb` that uses `selection`, `selection_mode`, `header_visible`, and `sort_indicator` data-binding support

## 0.7.2

- `table` `on_selection_changed` listener arguments now provide extra arguments of `selection`, `added_selection`, `removed_selection` after first argument (`table`)
- Update `examples/basic_table_selection.rb` to use new `on_selection_changed` arguments of `selection`, `added_selection`, and `removed_selection`

Cheers!
