### ISSUE TITLE
I want to write a button to mimic the close button and trigger WM_CLOSE.

### ISSUE THREAD

**Issue by Vucius** [AndyObtiva/glimmer-dsl-libui#43]
Code:
```
require 'glimmer-dsl-libui'

class MyWindow

  include Glimmer

  def initialize

    @window = window('Example Window', 300, 200) { |rrr|
      on_closing {
        puts 'Closing window...'
# **************
# do something
# *************
      }

      button('Close') {
        on_clicked do
          rrr.destroy
        end
      }

    }
  end
  def show
    @window.show
  end
end

MyWindow.new.show
```
The problem is that when rrr.destroy is executed, the window is closed but the program does not capture `WM_CLOSE` or exit. If I add the statement `LibUI.quit` after `rrr.destroy`, the program will exit directly. So I would like to know how to trigger sending a `WM_CLOSE` message to the program.
I am currently using `on_destroy` instead of `on_closing`. Although it has accomplished my task, I am still curious about how to trigger `on_closing`. Thank you.

**Comment by AndyObtiva** [comment]
`on_closing` is only triggered when you click the "x" button in the top-left corner of the window (or top-right depending on the operating system) to close it. There is no other way to programmatically trigger it. That is the reason why I added support for `on_destroy` in Glimmer DSL for LibUI. It's because there is no way to hook into `on_closing` if you close the window programmatically by calling `window_object.destroy`. Using `LibUI.quit` is the correct way to exit if you want to programmatically end the LibUI app after closing the window.

Given that you already have the solution, I am closing this issue. But, if you have further questions or are not satisifed with the answer, feel free to reply or even re-open the issue.

**Comment by AndyObtiva** [comment]
Setting the window position is an upcoming feature in LibUI-NG:
https://github.com/libui-ng/libui-ng/pull/62

Once it is released, it can be included in Glimmer DSL for LibUI.
