### ISSUE TITLE
Documentation for Simple Example

### ISSUE THREAD

**Issue by jakebruemmer** [AndyObtiva/glimmer-dsl-libui#59]
Hi there,

This library looks great, but I'm wondering if there is documentation in addition to some of the examples that are hosted in the repo. It's a little intimidating for someone that doesn't have any Lib UI experience, so maybe there is some documentation for beginners somewhere? I'm basically trying to make something that looks like the attached image. I can also close this and post it to StackOverflow if that'd be a better place, but I thought it would maybe be appropriate as an issue as there might be other beginners like me looking for this type of documentation.
![Untitled presentation](https://github.com/AndyObtiva/glimmer-dsl-libui/assets/7538587/da3b6047-8b07-42cc-88aa-9d650cd9a32e)

**Comment by AndyObtiva** [comment]
This code seems to accomlish your goal from testing on the Mac only at least:

```ruby
require 'glimmer-dsl-libui'

# This is a LoginRequest model
class LoginRequest
  ALLOWED_USERNAMES = %[john joe bob nancy gomez]
  
  attr_accessor :username
  
  def login
    ALLOWED_USERNAMES.include?(username.to_s.downcase)
  end
end

# By declaring this view as a Glimmer::LibUI::CustomWindow, you can later use `login_screen`
# as Glimmer GUI  keyword to instantiate LoginScreen underneath a parent
class LoginScreen
  include Glimmer::LibUI::CustomWindow
  
  attr_reader :login_result
  
  before_body do
    @login_request = LoginRequest.new
  end
  
  body {
    window('Login') {
      margined true
      
      vertical_box {
        form {
          entry {
            label 'Username:'
            text <=> [@login_request, :username]
          }
        }
        
        button('Login') {
          on_clicked do
            @login_result = @login_request.login
            # the following 2 lines close window and LibUI runtime for that window
            body_root.destroy
            ::LibUI.quit
          end
        }
      }
    }
  }
end

# By declaring this view as a Glimmer::LibUI::CustomWindow, you can later use `copy_screen`
# as Glimmer GUI  keyword to instantiate CopyScreen underneath a parent
class CopyScreen
  include Glimmer::LibUI::CustomWindow
  
  option :item
  
  body {
    window('Copy') {
      margined true
      
      label("Copying #{item} in progress...")
    }
  }
end

# By declaring this view as a Glimmer::LibUI::CustomWindow, you can later use `show_screen`
# as Glimmer GUI  keyword to instantiate ShowScreen underneath a parent
class ShowScreen
  include Glimmer::LibUI::CustomWindow
  
  option :item
  
  body {
    window('Copy') {
      margined true
      
      label("Showing #{item} content...")
    }
  }
end

class App
  include Glimmer::LibUI::Application
  
  ITEMS = 4.times.map {|n| "Item #{n+1}" }
  
  before_body do
    # login_screen builds an instance of LoginScreen
    login_window = login_screen
    # the show method will block until the window is closed
    login_window.show
    # if login result is false, then exit app completely
    if !login_window.login_result
      exit(0)
    end
  end
  
  body {
    window('App') {
      margined true
      
      vertical_box {
        ITEMS.each do |item|
          horizontal_box {
            label(item)
            
            button('Copy') {
              on_clicked do
                copy_screen(item: item).show
              end
            }
            
            button('Show') {
              on_clicked do
                show_screen(item: item).show
              end
            }
          }
        end
      }
    }
  }
end

App.launch
```

<img width="210" alt="Screenshot 2023-10-28 at 1 59 39 PM" src="https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/4aa8f0e4-07cf-4b4a-8b4e-8445b86eb77b">

<img width="218" alt="Screenshot 2023-10-28 at 1 59 42 PM" src="https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/0dc1fbba-ff0b-432b-a42b-18896e3b9f70">

<img width="213" alt="Screenshot 2023-10-28 at 2 04 43 PM" src="https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/a1c531e8-f7c0-4184-80da-ac5a6bd61fd2">

<img width="193" alt="Screenshot 2023-10-28 at 2 04 47 PM" src="https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/0dacd276-9681-4a8b-9d3c-94f2cccea711">

<img width="214" alt="Screenshot 2023-10-28 at 2 04 52 PM" src="https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/31a55c98-b878-4246-93b5-edc98115b93a">

<img width="195" alt="Screenshot 2023-10-28 at 2 04 56 PM" src="https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/2a796d44-a8a1-4580-9a40-73e0c4d0ee34">

At the bottom of the [README Usage section](https://github.com/AndyObtiva/glimmer-dsl-libui#usage), it says the following for Beginners (I probably should move this elsewhere to make it more prominent):

"If you are new to [Glimmer DSL for LibUI](https://rubygems.org/gems/glimmer-dsl-libui), check out the [Glimmer GUI DSL Concepts](https://github.com/AndyObtiva/glimmer-dsl-libui#glimmer-gui-dsl-concepts), [Glimmer Command](https://github.com/AndyObtiva/glimmer-dsl-libui#glimmer-command), [Girb](https://github.com/AndyObtiva/glimmer-dsl-libui#girb-glimmer-irb) and [Examples](https://github.com/AndyObtiva/glimmer-dsl-libui#examples) to quickly learn through copy/paste. You may refer to the [API](https://github.com/AndyObtiva/glimmer-dsl-libui#api) later on once you have gotten your feet wet with [Glimmer DSL for LibUI](https://rubygems.org/gems/glimmer-dsl-libui) and need more detailed reference information."

I think what matters the most are:
- [Glimmer GUI DSL Concepts](https://github.com/AndyObtiva/glimmer-dsl-libui#glimmer-gui-dsl-concepts)
- [Examples](https://github.com/AndyObtiva/glimmer-dsl-libui#examples)

Learn by going through every example (run locally) while searching the README for anything that matches what you see in the examples. You need to graduate gradually in knowledge on how to build desktop applications. 

Otherwise, I highly watching the RubyConf 2022 presentation on Building Native GUI Apps in Ruby:
https://www.youtube.com/watch?v=1Bh4CnJqHyY&feature=youtu.be

It breaks down the Glimmer DSL for LibUI concepts into small bits. But, you still need to apply the concepts by going through the [Examples](https://github.com/AndyObtiva/glimmer-dsl-libui#examples).

You are also welcome to ask me any questions here in Issues or on the [Glimmer Gitter chat](https://gitter.im/AndyObtiva/glimmer?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). I don't mind answering questions assuming an educated and serious Software Engineer.

In the meantime, if you could think of any improvements to documentation for beginners, please share ideas in Issues or doc submissions in Pull Requests.

**Comment by jakebruemmer** [comment]
Wow, this is incredibly helpful. I will try and put together a working copy today based off of this and let you know how it goes. Thank you!

**Comment by jakebruemmer** [comment]
Alright, I got something working locally and pushed an initial version to https://github.com/jakebruemmer/adamantite. 

I made a couple of tweaks to the code that you provided, but it's pretty much the same. Thank you for helping me understand the Glimmer UI lib a bit better. The creation and usage of classes makes a lot more sense now.

**Comment by AndyObtiva** [comment]
This is great news!! I am closing this issue as a result. 

If you think of any more questions in the future, you are welcome to ask me in the [Glimmer Gitter chat](https://gitter.im/AndyObtiva/glimmer?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or here if it’s related to the code mentioned above. 

Cheers.
